/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = function (knex) {
  // Kustutame kõik olemasolevad tooted
  return knex("products")
    .del()
    .then(function () {
      return knex("products").insert([
        {
          name: "Šokolaadi",
          description: "Maitsev šokolaadimesi.",
          price: 6.50,
          stock: 50,
          image_name: "šokolaadimesi",
          ingredients: "mesi, tume šokolaad",
          suitable_uses: "Sobib hästi määrdeks näiteks pannkoogile või saiale. Kuuma piimaga segades saab valmistada maitsvat kakaod.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Piim",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1632 kJ / 390 kcal",
            fats: "9,6 g",
            saturatedFats: "5,9 g",
            carbohydrates: "72,2 g",
            sugars: "70,7 g",
            proteins: "2,1 g",
            salt: "0,014 g",
          }),
        },
        {
          name: "Piparmündi-šokolaadi",
          description: "Šokolaadimesi piparmündiga.",
          price: 6.50,
          stock: 40,
          image_name: "piparmündi-šokolaadi",
          ingredients: "mesi, piparmündišokolaad",
          suitable_uses: "Sobib hästi määrdeks näiteks pannkoogile või saiale. Kuuma piimaga segades saab valmistada maitsvat piparmündi kakaod.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Piim",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1476 kJ / 353 kcal",
            fats: "3 g",
            saturatedFats: "1,7 g",
            carbohydrates: "79,2 g",
            sugars: "77 g",
            proteins: "0,9 g",
            salt: "0,014 g",
          }),
        },
        {
          name: "Kirsi-šokolaadi",
          description: "Šokolaadimesi kirsiga.",
          price: 6.50,
          stock: 30,
          image_name: "kirsi-šokolaadi",
          ingredients: "mesi, tume šokolaad, kirsi essents",
          suitable_uses: "Sobib hästi määrdeks näiteks pannkoogile või saiale.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Piim",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1632 kJ / 390 kcal",
            fats: "9,6 g",
            saturatedFats: "5,9 g",
            carbohydrates: "72,2 g",
            sugars: "70,7 g",
            proteins: "2,1 g",
            salt: "0,014 g",
          }),
        },
        {
          name: "Apelsini-šokolaadi",
          description: "Šokolaadimesi apelsiniga.",
          price: 6.50,
          stock: 60,
          image_name: "apelsini-šokolaadi",
          ingredients: "mesi, mündi-apelsinišokolaad",
          suitable_uses: "Sobib hästi määrdeks näiteks pannkoogile või saiale. Kuuma piimaga segades saab valmistada maitsvat apelsinikakaod.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Piim",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1532 kJ / 366 kcal",
            fats: "4,6 g",
            saturatedFats: "2,7 g",
            carbohydrates: "78,4 g",
            sugars: "76 g",
            proteins: "1,1 g",
            salt: "0,029 g",
          }),
        },
        {
          name: "Rummi-šokolaadi",
          description: "Rummiga rikastatud šokolaadimesi.",
          price: 6.50,
          stock: 20,
          image_name: "rummi-šokolaadi",
          ingredients: "mesi, tume šokolaad, rummi essents",
          suitable_uses: "Sobib hästi määrdeks näiteks pannkoogile või saiale. Kuuma piimaga segades saab valmistada maitsvat rummikakaod.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Piim",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1581 kJ / 378 kcal",
            fats: "8 g",
            saturatedFats: "5 g",
            carbohydrates: "73,1 g",
            sugars: "72,8 g",
            proteins: "2,3 g",
            salt: "0,049 g",
          }),
        },
        {
          name: "Maasika-jõhvika",
          description: "Maasika ja jõhvika maitseline mesi.",
          price: 6.50,
          stock: 45,
          image_name: "maasika-jõhvikamesi",
          ingredients: "mesi, kuivatatud ja jahvatatud maasikad ning jõhvikad",
          suitable_uses: "Sobib määrdeks näiteks saiale või pannkoogile. Segades seda meesegu tee sisse, annab see magusa lisamaitse.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Puuduvad",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1289 kJ / 308 kcal",
            fats: "0 g",
            saturatedFats: "0 g",
            carbohydrates: "75,1 g",
            sugars: "74,8 g",
            proteins: "0,6 g",
            salt: "0 g",
          }),
        },
        {
          name: "Astelpaju",
          description: "Tugevdav astelpaju mesi.",
          price: 6.50,
          stock: 35,
          image_name: "astelpajumesi",
          ingredients: "mesi, kuivatatud ja jahvatatud astelpaju marjad",
          suitable_uses: "Sobib määrdeks näiteks saiale või pannkoogile. Segades seda meesegu tee sisse, annab see magusa lisamaitse.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Puuduvad",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1308 kJ / 313 kcal",
            fats: "0 g",
            saturatedFats: "0 g",
            carbohydrates: "75,6 g",
            sugars: "75,3 g",
            proteins: "0,6 g",
            salt: "0 g",
          }),
        },
        {
          name: "Piparmündi",
          description: "Rahustav piparmündimaitseline mesi.",
          price: 6.50,
          stock: 50,
          image_name: "piparmündimesi",
          ingredients: "mesi, kuivatatud ja jahvatatud piparmünt",
          suitable_uses: "Sobib määrdeks näiteks saiale või pannkoogile. Segades seda meesegu kuuma vee sisse, saab valmistada maitsvat piparmündi teed.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Puuduvad",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1381 kJ / 330 kcal",
            fats: "0 g",
            saturatedFats: "0 g",
            carbohydrates: "82,5 g",
            sugars: "82,5 g",
            proteins: "0 g",
            salt: "0 g",
          }),
        },
        {
          name: "Ürdi-pipra",
          description: "Mõnus ürdi ja pipramaitseline mesi.",
          price: 6.50,
          stock: 25,
          image_name: "ürdi-piparmesí",
          ingredients: "mesi, erinevad piprad ja vürtsid",
          suitable_uses: "Toode on mõeldud ahjuliha marineerimiseks 4-5h enne ahju panemist. Soovitav on lisada sinepit ja veidi soola.",
          best_before: "7-9 kuud",
          net_weight: 240,
          allergens: "Puuduvad",
          price_per_100g: 2.71,
          nutrition: JSON.stringify({
            energy: "1073 kJ / 257 kcal",
            fats: "1,1 g",
            saturatedFats: "0 g",
            carbohydrates: "57,3 g",
            sugars: "54,3 g",
            proteins: "2,1 g",
            salt: "23 g",
          }),
        },
      ]);
    });
};
